from min_stack.MinStack import MinStack


s = MinStack()
s.push(5)
s.push(32)
s.push(2)
s.push(28)
print(s)
print("main peek:", s.peek())
print("min: ", s.getMin())
s.pop()
print(s)
print("main peek:", s.peek())
print("min: ", s.getMin())
s.pop()
print(s)
print("main peek:", s.peek())
print("min: ", s.getMin())
s.pop()
print(s)
print("main peek:", s.peek())
print("min: ", s.getMin())
print(s)
